version: '3.8'

services:
  flask:
    container_name: flask
    build:
      context: ./flask
      args:
        - STAGE

    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - flask